# Generated by Django 5.0.3 on 2024-04-11 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_product_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorderitems',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_item', to='core.cartorder'),
        ),
    ]
