# Generated by Django 5.0.3 on 2024-04-12 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_cartorderitems_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='date_order',
            field=models.DateTimeField(),
        ),
    ]
